language: node_js

node_js:
  - "0.10"

before_install:
 - sudo apt-get -y install gdb
 - npm install crash

install:
 - ulimit -c
 - ulimit -c unlimited -S
 - node -e "require('crash').crash()" || true
 - ls *
 - gdb `which node` core* -ex "thread apply all bt" -ex "set pagination 0" -batch
