environment:
  matrix:
    - nodejs_version: 0.11
    - nodejs_version: 0.10

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:Platform
  - ps: Start-FileDownload "https://mapnik.s3.amazonaws.com/dist/dev/VS-2014-runtime/vcredist_$env:Platform.exe"
  - .\vcredist_%platform%.exe /q /norestart
  - npm install

build: OFF
test: OFF
test_script: OFF
deploy: OFF
