environment:
  matrix:
    - nodejs_version: 0.11
    - nodejs_version: 0.10

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:Platform
  - npm install

build: OFF
test: OFF
test_script: OFF
deploy: OFF
